### ISSUE TITLE
Null Pointer Dereference Crash on 3-way Merge

### ISSUE THREAD

**Issue by daemonkeeper** [dolthub/dolt#1366]
I'm experimenting with dolt, and tried the conflict resolution behavior. For my test setup I've created simple dolt repository with simple tables with a foreign key:

```
$ dolt schema show
role @ working
CREATE TABLE `role` (
  `name` varchar(200) NOT NULL,
  `description` text,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

user @ working
CREATE TABLE `user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `first_name` varchar(200) DEFAULT NULL,
  `role_name` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `role_name` (`role_name`),
  CONSTRAINT `fl0v22us` FOREIGN KEY (`role_name`) REFERENCES `role` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

I did now add conflicting rows into master and a separate branch:

```
merge-comflict:
mysql> insert into role values ('#4', "merge conflict branch");
Query OK, 1 row affected (0.03 sec)

mysql> insert into user values (5, "Conflict", "Merge J.R.", "#4");
Query OK, 1 row affected (0.02 sec)

and master:
mysql> insert into role values ('#4', "master branch");
Query OK, 1 row affected (0.01 sec)

mysql> insert into user values (5, "Conflict", "Merge J.R. Master", "#4");
Query OK, 1 row affected (0.01 sec)
```

Trying to merge this togehter results in

```
$ dolt merge merge-conflict
Updating a1is08ne3bocfv6g92f3abnu3mv2fefk..jmk9i2vsun9o3o2p5k451v9dm8mlngqc
Auto-merging user
CONFLICT (content): Merge conflict in user
Auto-merging role
CONFLICT (content): Merge conflict in role
Automatic merge failed; fix conflicts and then commit the result.
$ dolt conflicts cat .
+-----+--------+----+----------+-------------------+-----------+
|     |        | id | name     | first_name        | role_name |
+-----+--------+----+----------+-------------------+-----------+
|  +  | ours   | 5  | Conflict | Merge J.R. Master | #4        |
|  +  | theirs | 5  | Conflict | Merge J.R.        | #4        |
+-----+--------+----+----------+-------------------+-----------+
+-----+--------+------+-----------------------+
|     |        | name | description           |
+-----+--------+------+-----------------------+
|  +  | ours   | #4   | master branch         |
|  +  | theirs | #4   | merge conflict branch |
+-----+--------+------+-----------------------+
$ dolt conflicts resolve role name
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c49c6e]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/doltdb.(*Table).HashOf(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/dolthub/dolt/go/libraries/doltcore/doltdb/table.go:334 +0x4e
github.com/dolthub/dolt/go/cmd/dolt/commands/cnfcmds.manualResolve(0x28b6900, 0xc00016a2d0, 0xc00016b140, 0xc00022a000, 0xc000124400, 0xc00016b140)
	github.com/dolthub/dolt/go/cmd/dolt/commands/cnfcmds/resolve.go:201 +0xaba
github.com/dolthub/dolt/go/cmd/dolt/commands/cnfcmds.ResolveCmd.Exec(0x28b6900, 0xc00016a2d0, 0xc000696160, 0x16, 0xc0001b4030, 0x2, 0x2, 0xc00022a000, 0x16)
	github.com/dolthub/dolt/go/cmd/dolt/commands/cnfcmds/resolve.go:110 +0x2cc
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x261ade7, 0x9, 0x2662d77, 0x33, 0xc000731460, 0x2, 0x2, 0x0, 0x28b6900, 0xc00016a2d0, ...)
	github.com/dolthub/dolt/go/cmd/dolt/cli/command.go:165 +0x4bd
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x2613602, 0x4, 0x2628438, 0x11, 0xc0003e0480, 0x24, 0x24, 0x0, 0x28b6880, 0xc00019e000, ...)
	github.com/dolthub/dolt/go/cmd/dolt/cli/command.go:165 +0x4bd
main.runMain(0x0)
	github.com/dolthub/dolt/go/cmd/dolt/dolt.go:251 +0xec9
main.main()
	github.com/dolthub/dolt/go/cmd/dolt/dolt.go:110 +0x25
```

This is running dolt 0.22.11 via Homebrew on MacOS X Catalina 10.15.7 

````
$ brew info dolt
zsh: correct 'dolt' to '.dolt' [nyae]? n
dolt: stable 0.22.11 (bottled)
Git for Data
https://github.com/liquidata-inc/dolt
/usr/local/Cellar/dolt/0.22.11 (7 files, 56.3MB) *
  Poured from bottle on 2021-01-29 at 16:15:05
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/dolt.rb
License: Apache-2.0
==> Dependencies
Build: go ✘
```

**Comment by andrew-wm-arthur** [comment]
@daemonkeeper Thanks for submitting this bug.

The nil pointer panic is resolved in the latest release, but the error messaging here still leaves room for improvement. The conflict resolution syntax you're using isn't quite right. You can choose to resolve the conflicts using "ours" or  "theirs":
`dolt conflict resolve --ours role`
or
` dolt conflict resolve --theirs user`

**Comment by daemonkeeper** [comment]
Thanks @andrew-wm-arthur, after upgrading the crash disappeared, but I still cannot do actual conflict resolution. I'm sorry to bug you here, but I couldn't find docs going through conflict resolution otherwise. How am I supposed to handle merge conflicts if I don't want to use --ours/--theirs, which essentially discards conflicting changes. 

I'm essentially trying to find out if this syntax would help me there:

``usage: dolt conflicts resolve <table> [<key_definition>] <key>...``
