### ISSUE TITLE
NULL in GROUP BY column is interpreted as 1

### ISSUE THREAD

**Issue by EmilyOng** [dolthub/dolt#9035]
Consider the following test case:

```sql
CREATE TABLE t0(c0 INT, c1 INT);
INSERT INTO t0(c0, c1) VALUES(NULL, 1), (1, NULL);
SELECT
    t0.c0 = t0.c1 AS ref0,
    SUM(1) AS ref1
FROM t0
GROUP BY ref0;
-- Issue also occurs in `GROUP BY 1` or `GROUP BY (t0.c0 = t0.c1)`.
```

Actual:
| ref0 | ref1 | 
| ---- | ---- |
| 1  | 2 | 

Expected:
| ref0 | ref1 | 
| ---- | ---- |
| null  | 2 | 

### Description

The expression `t0.c0 = t0.c1` evaluates to `null` for all rows in the table, since `=` is [not null-safe](https://dev.mysql.com/doc/refman/8.4/en/comparison-operators.html#operator_equal).

```sql
SELECT t0.c0 = t0.c1 AS ref0 FROM t0; -- null, null
```

So, both rows in the table belong to the same group with `null` as the group key. Hence, in the resulting table produced by GROUP BY, it is impossible to have a `1` in the GROUP BY column. So, the result is unexpected.

Moreover, the issue is interestingly not triggered in the following initialization statements, even though these initialization also each produce a single group with `null` as the group key.

1) Change `(1, NULL)` -> `(NULL, 1)`
```sql
CREATE TABLE t0(c0 INT , c1 INT);
INSERT INTO t0(c0, c1) VALUES(NULL, 1), (NULL, 1);
```

2) Change `(1, NULL)` -> `(NULL, NULL)`
```sql
CREATE TABLE t0(c0 INT , c1 INT);
INSERT INTO t0(c0, c1) VALUES(NULL, 1), (NULL, NULL);
```

### Dolt Version

This issue occurred when using Dolt via the Docker image [dolthub/dolt-sql-server:1.50.9](https://hub.docker.com/layers/dolthub/dolt-sql-server/1.50.9/images/sha256-d94ceab08de3861bea685b1473ec7586a05e8488593ebb24b6e1f1815fd07805).

I also reproduced this issue by installing Dolt via the latest  release using the [command](https://github.com/dolthub/dolt?tab=readme-ov-file#from-latest-release).

<details>
<summary> Output </summary>

```
└─╼ [emilyong@Emilys-MacBook-Air] ╾─╼ [~] dolt version
dolt version 1.50.9
└─╼ [emilyong@Emilys-MacBook-Air] ╾─╼ [~] dolt sql    
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit. "\help" for help.
> CREATE DATABASE d0;
Empty set (0.34 sec)

> USE d0;
Database changed
d0/main> CREATE TABLE t0(c0 INT, c1 INT);
d0/main*> INSERT INTO t0(c0, c1) VALUES(NULL, 1), (1, NULL);
Empty set (0.01 sec)

d0/main*> SELECT t0.c0 = t0.c1 AS ref0, SUM(1) AS ref1 FROM t0 GROUP BY ref0;
+------+------+
| ref0 | ref1 |
+------+------+
| 1    | 2    |
+------+------+
1 row in set (0.00 sec)
```

**Comment by timsehn** [comment]
Thanks for the detailed repro. We'll try and bang these three bugs out today.

**Comment by timsehn** [comment]
This is fixed by:

https://github.com/dolthub/go-mysql-server/pull/2912

**Comment by EmilyOng** [comment]
Hi! Correct me if I'm wrong, but the linked PR appears to be related to another issue, and this bug still remains in 1.51.1. I checked it by running the following snippet:

```
> CREATE DATABASE d0;
Empty set (0.32 sec)

> USE d0;
Database changed
d0/main> CREATE TABLE t0(c0 INT, c1 INT);
d0/main*> INSERT INTO t0(c0, c1) VALUES(NULL, 1), (1, NULL);
Empty set (0.01 sec)

d0/main*> SELECT
       ->     t0.c0 = t0.c1 AS ref0,
       ->     SUM(1) AS ref1
       -> FROM t0
       -> GROUP BY ref0;
+------+------+
| ref0 | ref1 |
+------+------+
| 1    | 2    |
+------+------+
1 row in set (0.00 sec)

d0/main*> SELECT dolt_version();
+----------------+
| dolt_version() |
+----------------+
| 1.51.1         |
+----------------+
1 row in set (0.00 sec)
```

Thanks for looking into this issue and for the swift fixes!

**Comment by timsehn** [comment]
My bad,

**Comment by timsehn** [comment]
Are you running a test suite on Dolt or are these bugs blocking your adoption? 

This one in p[articular is a bit tricky and @max-hoffman is working on a larger fix for another customer. We're wondering if we should fix the point case or wait for the larger fix?

**Comment by EmilyOng** [comment]
@timsehn I'm running a test suite on Dolt, and it's fine to wait for the larger fix. Thanks again!
