### ISSUE TITLE
varbinary fields are presented as unicode instead of hex

### ISSUE THREAD

**Issue by glennmatthews** [dolthub/dolt#9554]
This may be related to #8893?

I'm noticing with Dolt 1.57.0 that varbinary fields are defaulting to being rendered as unicode strings (which naturally doesn't render very well when they are binary data rather than strings) instead of as hexadecimal as they are in MySQL. 

### MySQL:

```
mysql> select network from ipam_prefix limit 10;
+------------------+
| network          |
+------------------+
| 0x0A000000       |
| 0x0A000000       |
| 0x0A004000       |
| 0x0A008000       |
| 0x0A00C000       |
| 0x0A010000       |
| 0x0A010000       |
| 0x0A014000       |
| 0x0A018000       |
| 0x0A020000       |
+------------------+
10 rows in set (0.00 sec)
```

```
mysql> select HEX(network) from ipam_prefix limit 10;
+--------------+
| HEX(network) |
+--------------+
| 0A000000     |
| 0A000000     |
| 0A004000     |
| 0A008000     |
| 0A00C000     |
| 0A010000     |
| 0A010000     |
| 0A014000     |
| 0A018000     |
| 0A020000     |
+--------------+
10 rows in set (0.00 sec)
```

### Dolt:

```
> SELECT network FROM ipam_prefix limit 10;
+------------------+
| network          |
+------------------+
�   �        |
| 
�              |
| 
               |
�            |
| 
 �              |
| 
               |
| 
�              |
�            |
| 
�              |
| 
�             |
+------------------+
10 rows in set (0.002 sec)
```

```
> SELECT HEX(network) FROM ipam_prefix limit 10;
+----------------------------------+
| HEX(network)                     |
+----------------------------------+
| 20010DB8000000028000000000000000 |
| 0A1DC000                         |
| 0A0E0000                         |
| 20010DB8000000020000000000000000 |
| 0A00C000                         |
| 0A180000                         |
| 0A108000                         |
| 20010DB8000000130000000000000000 |
| 0A068000                         |
| 0A1B8000                         |
+----------------------------------+
10 rows in set (0.001 sec)
```

**Comment by glennmatthews** [comment]
Hi, is there some nuance to how I have to configure Dolt and/or the MySQL client in order to get this to work? I'm still seeing the old behavior in 1.57.4:

```sql
MySQL [test_nautobot]> select dolt_version();
+----------------+
| dolt_version() |
+----------------+
| 1.57.4         |
+----------------+
1 row in set (0.000 sec)

MySQL [test_nautobot]> select network from ipam_prefix limit 10;
+------------------+
| network          |
+------------------+
�            |
| 
               |
| 
               |
| 
�              |
�   (         |
| 
	               |
| 
	               |
| 
@              |
| 
               |
�   "         |
+------------------+
10 rows in set (0.000 sec)
```

**Comment by elianddb** [comment]
@glennmatthews the latest release should contain this feature now, sorry for the wait! Like MySQL, the hex format is shown in an interactive shell. To see it in non-interactive use the --binary-as-hex flag after your query.

**Comment by glennmatthews** [comment]
Is that only with `dolt sql`? Or what's the expected behavior for a generic MySQL client?

**Comment by elianddb** [comment]
Only with `dolt sql`, however, if you do use the flag you can overwrite the default behavior for non-interactive actions such as `dolt sql -q "query" --binary-as-hex`

**Comment by elianddb** [comment]
I misunderstood, this is only fixed in `dolt sql` working on a fix for the generic mysql client.

**Comment by elianddb** [comment]
@glennmatthews Did some further testing the previous fix did fix the generic MySQL client too. It shows hex by default for both `mysql` and `mysql -e`. You can use the `--skip-binary-as-hex` to skip this.

**Comment by glennmatthews** [comment]
I'm confused still because even with dolt 1.57.6 I'm still seeing binary output from the client:

```
root@437feb7b2330:/var/lib/dolt# mysql -u nautobot -p -h 127.0.0.1
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 615
Server version: 8.0.33 Dolt

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> use test_nautobot;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MySQL [test_nautobot]> select host from ipam_ipaddress limit 10;
+------------------+
| host             |
+------------------+
| 
�             |
�           |
| 
@             |
�   "        |
�   �       |
�          
 |
| 
@             |
�   �       |
�   (        |
�   $�       |
+------------------+
10 rows in set (0.000 sec)

MySQL [test_nautobot]> select dolt_version();
+----------------+
| dolt_version() |
+----------------+
| 1.57.6         |
+----------------+
1 row in set (0.000 sec)
```

I do see that if I explicitly specify `mysql --binary-as-hex` that I get the correct behavior but that doesn't seem to align with your last comment above that it should do so by default.

```
root@437feb7b2330:/var/lib/dolt# mysql --binary-as-hex -u nautobot -p -h 127.0.0.1
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 712
Server version: 8.0.33 Dolt

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> use test_nautobot;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MySQL [test_nautobot]> select host from ipam_ipaddress limit 10;
+------------------------------------+
| host                               |
+------------------------------------+
| 0x0A198004                         |
| 0x20010DB8000000020000000000000004 |
| 0x0A064001                         |
| 0x20010DB8000000220000000000000001 |
| 0x20010DB8000000048000000000000003 |
| 0x20010DB800000005000000000000000A |
| 0x0A064005                         |
| 0x20010DB8000000058000000000000001 |
| 0x20010DB8000000280000000000000007 |
| 0x20010DB8000000248000000000000001 |
+------------------------------------+
10 rows in set (0.000 sec)
```

**Comment by glennmatthews** [comment]
Ah. appears to be a difference in defaults between differing versions of mysql/mariadb clients. My apologies for the confusion.
